// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVeakp3sqNWsJIA9XNh57GQ-kh5T2INeA',
    appId: '1:136972253756:web:a04c29e8a9e097409e2139',
    messagingSenderId: '136972253756',
    projectId: 'scrolls-33650',
    authDomain: 'scrolls-33650.firebaseapp.com',
    storageBucket: 'scrolls-33650.appspot.com',
    measurementId: 'G-ZXL18BPK9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKzWmxu1KxId5bl7_gl7LnJQm8nMSabQ',
    appId: '1:136972253756:android:938d34c11b8df47c9e2139',
    messagingSenderId: '136972253756',
    projectId: 'scrolls-33650',
    storageBucket: 'scrolls-33650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClOiSDDozfV3yo8ZTeeMo-gPd6JuxfBLM',
    appId: '1:136972253756:ios:267d436521b5ad079e2139',
    messagingSenderId: '136972253756',
    projectId: 'scrolls-33650',
    storageBucket: 'scrolls-33650.appspot.com',
    iosBundleId: 'com.example.scrolls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClOiSDDozfV3yo8ZTeeMo-gPd6JuxfBLM',
    appId: '1:136972253756:ios:81048a7e35b30a139e2139',
    messagingSenderId: '136972253756',
    projectId: 'scrolls-33650',
    storageBucket: 'scrolls-33650.appspot.com',
    iosBundleId: 'com.example.scrolls.RunnerTests',
  );
}
